#let kehrwoche(plan_name: str, year: int, rows: array) = [
  = Kehrwoche: #plan_name (#year)

  #table(
    columns: 5,
    table.header([Week], [Start], [End], [Name], [Email]),
    for row in rows [
      [#row.week], [#row.start], [#row.end], [#row.name], [#row.email],
    ],
  )

  #v(8pt)
  #text(size: 8pt)[Generated by Kehrkraft]
]
